version: '3.7'

services:
  redis:
    image: redis:6

  roadrunner:
    container_name: roadrunner
    environment:
      - GOGC=100
    ulimits:
      nofile:
        soft: 65000
        hard: 65000
      mem_limit: 1024
      cpus: 1
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.local
    command: "serve -c /etc/rr-docker.yaml -d"
    ports:
      - "15395:15395"
      - "6061:6061"
      - "6001:6001"
